package com.app.model;

public class TRClassStudent {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_r_class_student.id
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_r_class_student.student_id
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    private String student_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_r_class_student.class_id
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    private String class_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_r_class_student.student_course_num
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    private Integer student_course_num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_r_class_student.class_status
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    private Boolean class_status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_r_class_student.is_delete
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    private Boolean is_delete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_r_class_student.create_time
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    private Long create_time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_r_class_student.update_time
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    private Long update_time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_r_class_student.id
     *
     * @return the value of t_r_class_student.id
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_r_class_student.id
     *
     * @param id the value for t_r_class_student.id
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_r_class_student.student_id
     *
     * @return the value of t_r_class_student.student_id
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public String getStudent_id() {
        return student_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_r_class_student.student_id
     *
     * @param student_id the value for t_r_class_student.student_id
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public void setStudent_id(String student_id) {
        this.student_id = student_id == null ? null : student_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_r_class_student.class_id
     *
     * @return the value of t_r_class_student.class_id
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public String getClass_id() {
        return class_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_r_class_student.class_id
     *
     * @param class_id the value for t_r_class_student.class_id
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public void setClass_id(String class_id) {
        this.class_id = class_id == null ? null : class_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_r_class_student.student_course_num
     *
     * @return the value of t_r_class_student.student_course_num
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public Integer getStudent_course_num() {
        return student_course_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_r_class_student.student_course_num
     *
     * @param student_course_num the value for t_r_class_student.student_course_num
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public void setStudent_course_num(Integer student_course_num) {
        this.student_course_num = student_course_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_r_class_student.class_status
     *
     * @return the value of t_r_class_student.class_status
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public Boolean getClass_status() {
        return class_status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_r_class_student.class_status
     *
     * @param class_status the value for t_r_class_student.class_status
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public void setClass_status(Boolean class_status) {
        this.class_status = class_status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_r_class_student.is_delete
     *
     * @return the value of t_r_class_student.is_delete
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public Boolean getIs_delete() {
        return is_delete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_r_class_student.is_delete
     *
     * @param is_delete the value for t_r_class_student.is_delete
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public void setIs_delete(Boolean is_delete) {
        this.is_delete = is_delete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_r_class_student.create_time
     *
     * @return the value of t_r_class_student.create_time
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public Long getCreate_time() {
        return create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_r_class_student.create_time
     *
     * @param create_time the value for t_r_class_student.create_time
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public void setCreate_time(Long create_time) {
        this.create_time = create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_r_class_student.update_time
     *
     * @return the value of t_r_class_student.update_time
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public Long getUpdate_time() {
        return update_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_r_class_student.update_time
     *
     * @param update_time the value for t_r_class_student.update_time
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public void setUpdate_time(Long update_time) {
        this.update_time = update_time;
    }
}