package com.app.model;

public class TRUserStudent {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_r_user_student.id
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_r_user_student.rid
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    private String rid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_r_user_student.user_phone
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    private Integer user_phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_r_user_student.student_id
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    private String student_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_r_user_student.relation
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    private String relation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_r_user_student.create_time
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    private Long create_time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_r_user_student.update_time
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    private Long update_time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_r_user_student.id
     *
     * @return the value of t_r_user_student.id
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_r_user_student.id
     *
     * @param id the value for t_r_user_student.id
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_r_user_student.rid
     *
     * @return the value of t_r_user_student.rid
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public String getRid() {
        return rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_r_user_student.rid
     *
     * @param rid the value for t_r_user_student.rid
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public void setRid(String rid) {
        this.rid = rid == null ? null : rid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_r_user_student.user_phone
     *
     * @return the value of t_r_user_student.user_phone
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public Integer getUser_phone() {
        return user_phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_r_user_student.user_phone
     *
     * @param user_phone the value for t_r_user_student.user_phone
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public void setUser_phone(Integer user_phone) {
        this.user_phone = user_phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_r_user_student.student_id
     *
     * @return the value of t_r_user_student.student_id
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public String getStudent_id() {
        return student_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_r_user_student.student_id
     *
     * @param student_id the value for t_r_user_student.student_id
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public void setStudent_id(String student_id) {
        this.student_id = student_id == null ? null : student_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_r_user_student.relation
     *
     * @return the value of t_r_user_student.relation
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public String getRelation() {
        return relation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_r_user_student.relation
     *
     * @param relation the value for t_r_user_student.relation
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public void setRelation(String relation) {
        this.relation = relation == null ? null : relation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_r_user_student.create_time
     *
     * @return the value of t_r_user_student.create_time
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public Long getCreate_time() {
        return create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_r_user_student.create_time
     *
     * @param create_time the value for t_r_user_student.create_time
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public void setCreate_time(Long create_time) {
        this.create_time = create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_r_user_student.update_time
     *
     * @return the value of t_r_user_student.update_time
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public Long getUpdate_time() {
        return update_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_r_user_student.update_time
     *
     * @param update_time the value for t_r_user_student.update_time
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public void setUpdate_time(Long update_time) {
        this.update_time = update_time;
    }
}