package com.jckj.model;

public class TCourseInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_course_info.id
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_course_info.course_name
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    private String course_name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_course_info.course_time
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    private Long course_time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_course_info.photo
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    private String photo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_course_info.course_introduce
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    private String course_introduce;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_course_info.course_price
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    private String course_price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_course_info.tocourse_bigin_time
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    private Long tocourse_bigin_time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_course_info.tocourse_finish_time
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    private Long tocourse_finish_time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_course_info.enroll_total
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    private String enroll_total;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_course_info.is_shaky
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    private Boolean is_shaky;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_course_info.course_state
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    private Boolean course_state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_course_info.school_name
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    private String school_name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_course_info.is_delete
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    private Byte is_delete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_course_info.create_time
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    private Long create_time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_course_info.update_time
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    private Long update_time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course_info.id
     *
     * @return the value of t_course_info.id
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course_info.id
     *
     * @param id the value for t_course_info.id
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course_info.course_name
     *
     * @return the value of t_course_info.course_name
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public String getCourse_name() {
        return course_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course_info.course_name
     *
     * @param course_name the value for t_course_info.course_name
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public void setCourse_name(String course_name) {
        this.course_name = course_name == null ? null : course_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course_info.course_time
     *
     * @return the value of t_course_info.course_time
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public Long getCourse_time() {
        return course_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course_info.course_time
     *
     * @param course_time the value for t_course_info.course_time
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public void setCourse_time(Long course_time) {
        this.course_time = course_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course_info.photo
     *
     * @return the value of t_course_info.photo
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public String getPhoto() {
        return photo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course_info.photo
     *
     * @param photo the value for t_course_info.photo
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public void setPhoto(String photo) {
        this.photo = photo == null ? null : photo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course_info.course_introduce
     *
     * @return the value of t_course_info.course_introduce
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public String getCourse_introduce() {
        return course_introduce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course_info.course_introduce
     *
     * @param course_introduce the value for t_course_info.course_introduce
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public void setCourse_introduce(String course_introduce) {
        this.course_introduce = course_introduce == null ? null : course_introduce.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course_info.course_price
     *
     * @return the value of t_course_info.course_price
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public String getCourse_price() {
        return course_price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course_info.course_price
     *
     * @param course_price the value for t_course_info.course_price
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public void setCourse_price(String course_price) {
        this.course_price = course_price == null ? null : course_price.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course_info.tocourse_bigin_time
     *
     * @return the value of t_course_info.tocourse_bigin_time
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public Long getTocourse_bigin_time() {
        return tocourse_bigin_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course_info.tocourse_bigin_time
     *
     * @param tocourse_bigin_time the value for t_course_info.tocourse_bigin_time
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public void setTocourse_bigin_time(Long tocourse_bigin_time) {
        this.tocourse_bigin_time = tocourse_bigin_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course_info.tocourse_finish_time
     *
     * @return the value of t_course_info.tocourse_finish_time
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public Long getTocourse_finish_time() {
        return tocourse_finish_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course_info.tocourse_finish_time
     *
     * @param tocourse_finish_time the value for t_course_info.tocourse_finish_time
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public void setTocourse_finish_time(Long tocourse_finish_time) {
        this.tocourse_finish_time = tocourse_finish_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course_info.enroll_total
     *
     * @return the value of t_course_info.enroll_total
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public String getEnroll_total() {
        return enroll_total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course_info.enroll_total
     *
     * @param enroll_total the value for t_course_info.enroll_total
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public void setEnroll_total(String enroll_total) {
        this.enroll_total = enroll_total == null ? null : enroll_total.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course_info.is_shaky
     *
     * @return the value of t_course_info.is_shaky
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public Boolean getIs_shaky() {
        return is_shaky;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course_info.is_shaky
     *
     * @param is_shaky the value for t_course_info.is_shaky
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public void setIs_shaky(Boolean is_shaky) {
        this.is_shaky = is_shaky;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course_info.course_state
     *
     * @return the value of t_course_info.course_state
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public Boolean getCourse_state() {
        return course_state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course_info.course_state
     *
     * @param course_state the value for t_course_info.course_state
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public void setCourse_state(Boolean course_state) {
        this.course_state = course_state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course_info.school_name
     *
     * @return the value of t_course_info.school_name
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public String getSchool_name() {
        return school_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course_info.school_name
     *
     * @param school_name the value for t_course_info.school_name
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public void setSchool_name(String school_name) {
        this.school_name = school_name == null ? null : school_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course_info.is_delete
     *
     * @return the value of t_course_info.is_delete
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public Byte getIs_delete() {
        return is_delete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course_info.is_delete
     *
     * @param is_delete the value for t_course_info.is_delete
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public void setIs_delete(Byte is_delete) {
        this.is_delete = is_delete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course_info.create_time
     *
     * @return the value of t_course_info.create_time
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public Long getCreate_time() {
        return create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course_info.create_time
     *
     * @param create_time the value for t_course_info.create_time
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public void setCreate_time(Long create_time) {
        this.create_time = create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course_info.update_time
     *
     * @return the value of t_course_info.update_time
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public Long getUpdate_time() {
        return update_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course_info.update_time
     *
     * @param update_time the value for t_course_info.update_time
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public void setUpdate_time(Long update_time) {
        this.update_time = update_time;
    }
}