package com.jckj.model;

public class TEnrollInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_enroll_info.id
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_enroll_info.student_name
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    private String student_name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_enroll_info.user_phone
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    private String user_phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_enroll_info.pattern
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    private String pattern;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_enroll_info.canal
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    private String canal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_enroll_info.class hour
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    private String class_hour;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_enroll_info.school_name
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    private String school_name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_enroll_info.enroll_state
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    private Boolean enroll_state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_enroll_info.course_hour
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    private Integer course_hour;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_enroll_info.course_name
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    private String course_name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_enroll_info.is_delete
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    private Boolean is_delete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_enroll_info.create_time
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    private Long create_time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_enroll_info.update_time
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    private Long update_time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_enroll_info.id
     *
     * @return the value of t_enroll_info.id
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_enroll_info.id
     *
     * @param id the value for t_enroll_info.id
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_enroll_info.student_name
     *
     * @return the value of t_enroll_info.student_name
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public String getStudent_name() {
        return student_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_enroll_info.student_name
     *
     * @param student_name the value for t_enroll_info.student_name
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public void setStudent_name(String student_name) {
        this.student_name = student_name == null ? null : student_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_enroll_info.user_phone
     *
     * @return the value of t_enroll_info.user_phone
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public String getUser_phone() {
        return user_phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_enroll_info.user_phone
     *
     * @param user_phone the value for t_enroll_info.user_phone
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public void setUser_phone(String user_phone) {
        this.user_phone = user_phone == null ? null : user_phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_enroll_info.pattern
     *
     * @return the value of t_enroll_info.pattern
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public String getPattern() {
        return pattern;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_enroll_info.pattern
     *
     * @param pattern the value for t_enroll_info.pattern
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public void setPattern(String pattern) {
        this.pattern = pattern == null ? null : pattern.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_enroll_info.canal
     *
     * @return the value of t_enroll_info.canal
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public String getCanal() {
        return canal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_enroll_info.canal
     *
     * @param canal the value for t_enroll_info.canal
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public void setCanal(String canal) {
        this.canal = canal == null ? null : canal.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_enroll_info.class hour
     *
     * @return the value of t_enroll_info.class hour
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public String getClass_hour() {
        return class_hour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_enroll_info.class hour
     *
     * @param class_hour the value for t_enroll_info.class hour
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public void setClass_hour(String class_hour) {
        this.class_hour = class_hour == null ? null : class_hour.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_enroll_info.school_name
     *
     * @return the value of t_enroll_info.school_name
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public String getSchool_name() {
        return school_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_enroll_info.school_name
     *
     * @param school_name the value for t_enroll_info.school_name
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public void setSchool_name(String school_name) {
        this.school_name = school_name == null ? null : school_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_enroll_info.enroll_state
     *
     * @return the value of t_enroll_info.enroll_state
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public Boolean getEnroll_state() {
        return enroll_state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_enroll_info.enroll_state
     *
     * @param enroll_state the value for t_enroll_info.enroll_state
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public void setEnroll_state(Boolean enroll_state) {
        this.enroll_state = enroll_state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_enroll_info.course_hour
     *
     * @return the value of t_enroll_info.course_hour
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public Integer getCourse_hour() {
        return course_hour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_enroll_info.course_hour
     *
     * @param course_hour the value for t_enroll_info.course_hour
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public void setCourse_hour(Integer course_hour) {
        this.course_hour = course_hour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_enroll_info.course_name
     *
     * @return the value of t_enroll_info.course_name
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public String getCourse_name() {
        return course_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_enroll_info.course_name
     *
     * @param course_name the value for t_enroll_info.course_name
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public void setCourse_name(String course_name) {
        this.course_name = course_name == null ? null : course_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_enroll_info.is_delete
     *
     * @return the value of t_enroll_info.is_delete
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public Boolean getIs_delete() {
        return is_delete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_enroll_info.is_delete
     *
     * @param is_delete the value for t_enroll_info.is_delete
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public void setIs_delete(Boolean is_delete) {
        this.is_delete = is_delete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_enroll_info.create_time
     *
     * @return the value of t_enroll_info.create_time
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public Long getCreate_time() {
        return create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_enroll_info.create_time
     *
     * @param create_time the value for t_enroll_info.create_time
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public void setCreate_time(Long create_time) {
        this.create_time = create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_enroll_info.update_time
     *
     * @return the value of t_enroll_info.update_time
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public Long getUpdate_time() {
        return update_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_enroll_info.update_time
     *
     * @param update_time the value for t_enroll_info.update_time
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public void setUpdate_time(Long update_time) {
        this.update_time = update_time;
    }
}