package com.jckj.model;

public class TGradeInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_grade_info.id
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_grade_info.grade_name
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    private String grade_name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_grade_info.grade_time
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    private Long grade_time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_grade_info.coach_name
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    private String coach_name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_grade_info.grade_photo
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    private String grade_photo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_grade_info.describe
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    private String describe;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_grade_info.grade_status
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    private Boolean grade_status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_grade_info.school_name
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    private String school_name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_grade_info.is_delete
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    private Boolean is_delete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_grade_info.create_time
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    private Long create_time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_grade_info.update_time
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    private Long update_time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_grade_info.id
     *
     * @return the value of t_grade_info.id
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_grade_info.id
     *
     * @param id the value for t_grade_info.id
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_grade_info.grade_name
     *
     * @return the value of t_grade_info.grade_name
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public String getGrade_name() {
        return grade_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_grade_info.grade_name
     *
     * @param grade_name the value for t_grade_info.grade_name
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public void setGrade_name(String grade_name) {
        this.grade_name = grade_name == null ? null : grade_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_grade_info.grade_time
     *
     * @return the value of t_grade_info.grade_time
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public Long getGrade_time() {
        return grade_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_grade_info.grade_time
     *
     * @param grade_time the value for t_grade_info.grade_time
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public void setGrade_time(Long grade_time) {
        this.grade_time = grade_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_grade_info.coach_name
     *
     * @return the value of t_grade_info.coach_name
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public String getCoach_name() {
        return coach_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_grade_info.coach_name
     *
     * @param coach_name the value for t_grade_info.coach_name
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public void setCoach_name(String coach_name) {
        this.coach_name = coach_name == null ? null : coach_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_grade_info.grade_photo
     *
     * @return the value of t_grade_info.grade_photo
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public String getGrade_photo() {
        return grade_photo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_grade_info.grade_photo
     *
     * @param grade_photo the value for t_grade_info.grade_photo
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public void setGrade_photo(String grade_photo) {
        this.grade_photo = grade_photo == null ? null : grade_photo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_grade_info.describe
     *
     * @return the value of t_grade_info.describe
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public String getDescribe() {
        return describe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_grade_info.describe
     *
     * @param describe the value for t_grade_info.describe
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public void setDescribe(String describe) {
        this.describe = describe == null ? null : describe.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_grade_info.grade_status
     *
     * @return the value of t_grade_info.grade_status
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public Boolean getGrade_status() {
        return grade_status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_grade_info.grade_status
     *
     * @param grade_status the value for t_grade_info.grade_status
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public void setGrade_status(Boolean grade_status) {
        this.grade_status = grade_status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_grade_info.school_name
     *
     * @return the value of t_grade_info.school_name
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public String getSchool_name() {
        return school_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_grade_info.school_name
     *
     * @param school_name the value for t_grade_info.school_name
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public void setSchool_name(String school_name) {
        this.school_name = school_name == null ? null : school_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_grade_info.is_delete
     *
     * @return the value of t_grade_info.is_delete
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public Boolean getIs_delete() {
        return is_delete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_grade_info.is_delete
     *
     * @param is_delete the value for t_grade_info.is_delete
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public void setIs_delete(Boolean is_delete) {
        this.is_delete = is_delete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_grade_info.create_time
     *
     * @return the value of t_grade_info.create_time
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public Long getCreate_time() {
        return create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_grade_info.create_time
     *
     * @param create_time the value for t_grade_info.create_time
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public void setCreate_time(Long create_time) {
        this.create_time = create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_grade_info.update_time
     *
     * @return the value of t_grade_info.update_time
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public Long getUpdate_time() {
        return update_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_grade_info.update_time
     *
     * @param update_time the value for t_grade_info.update_time
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public void setUpdate_time(Long update_time) {
        this.update_time = update_time;
    }
}