package com.jckj.model;

public class TMienInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mien_info.id
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mien_info.student_id
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    private Integer student_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mien_info.mien_photo
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    private String mien_photo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mien_info.mien_video
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    private String mien_video;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mien_info.mien_status
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    private Boolean mien_status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mien_info.school_name
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    private String school_name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mien_info.is_delete
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    private Boolean is_delete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mien_info.create_time
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    private Long create_time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mien_info.update_time
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    private Long update_time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mien_info.id
     *
     * @return the value of t_mien_info.id
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mien_info.id
     *
     * @param id the value for t_mien_info.id
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mien_info.student_id
     *
     * @return the value of t_mien_info.student_id
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public Integer getStudent_id() {
        return student_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mien_info.student_id
     *
     * @param student_id the value for t_mien_info.student_id
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public void setStudent_id(Integer student_id) {
        this.student_id = student_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mien_info.mien_photo
     *
     * @return the value of t_mien_info.mien_photo
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public String getMien_photo() {
        return mien_photo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mien_info.mien_photo
     *
     * @param mien_photo the value for t_mien_info.mien_photo
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public void setMien_photo(String mien_photo) {
        this.mien_photo = mien_photo == null ? null : mien_photo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mien_info.mien_video
     *
     * @return the value of t_mien_info.mien_video
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public String getMien_video() {
        return mien_video;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mien_info.mien_video
     *
     * @param mien_video the value for t_mien_info.mien_video
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public void setMien_video(String mien_video) {
        this.mien_video = mien_video == null ? null : mien_video.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mien_info.mien_status
     *
     * @return the value of t_mien_info.mien_status
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public Boolean getMien_status() {
        return mien_status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mien_info.mien_status
     *
     * @param mien_status the value for t_mien_info.mien_status
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public void setMien_status(Boolean mien_status) {
        this.mien_status = mien_status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mien_info.school_name
     *
     * @return the value of t_mien_info.school_name
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public String getSchool_name() {
        return school_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mien_info.school_name
     *
     * @param school_name the value for t_mien_info.school_name
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public void setSchool_name(String school_name) {
        this.school_name = school_name == null ? null : school_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mien_info.is_delete
     *
     * @return the value of t_mien_info.is_delete
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public Boolean getIs_delete() {
        return is_delete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mien_info.is_delete
     *
     * @param is_delete the value for t_mien_info.is_delete
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public void setIs_delete(Boolean is_delete) {
        this.is_delete = is_delete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mien_info.create_time
     *
     * @return the value of t_mien_info.create_time
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public Long getCreate_time() {
        return create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mien_info.create_time
     *
     * @param create_time the value for t_mien_info.create_time
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public void setCreate_time(Long create_time) {
        this.create_time = create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mien_info.update_time
     *
     * @return the value of t_mien_info.update_time
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public Long getUpdate_time() {
        return update_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mien_info.update_time
     *
     * @param update_time the value for t_mien_info.update_time
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public void setUpdate_time(Long update_time) {
        this.update_time = update_time;
    }
}