package com.jckj.model;

public class TOpenRotation {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_open_rotation.id
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_open_rotation.school_photo
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    private String school_photo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_open_rotation.is_show
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    private Boolean is_show;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_open_rotation.is_delete
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    private Boolean is_delete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_open_rotation.sequence
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    private Integer sequence;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_open_rotation.create_time
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    private Long create_time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_open_rotation.update_time
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    private Long update_time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_open_rotation.id
     *
     * @return the value of t_open_rotation.id
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_open_rotation.id
     *
     * @param id the value for t_open_rotation.id
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_open_rotation.school_photo
     *
     * @return the value of t_open_rotation.school_photo
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public String getSchool_photo() {
        return school_photo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_open_rotation.school_photo
     *
     * @param school_photo the value for t_open_rotation.school_photo
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public void setSchool_photo(String school_photo) {
        this.school_photo = school_photo == null ? null : school_photo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_open_rotation.is_show
     *
     * @return the value of t_open_rotation.is_show
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public Boolean getIs_show() {
        return is_show;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_open_rotation.is_show
     *
     * @param is_show the value for t_open_rotation.is_show
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public void setIs_show(Boolean is_show) {
        this.is_show = is_show;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_open_rotation.is_delete
     *
     * @return the value of t_open_rotation.is_delete
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public Boolean getIs_delete() {
        return is_delete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_open_rotation.is_delete
     *
     * @param is_delete the value for t_open_rotation.is_delete
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public void setIs_delete(Boolean is_delete) {
        this.is_delete = is_delete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_open_rotation.sequence
     *
     * @return the value of t_open_rotation.sequence
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public Integer getSequence() {
        return sequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_open_rotation.sequence
     *
     * @param sequence the value for t_open_rotation.sequence
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public void setSequence(Integer sequence) {
        this.sequence = sequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_open_rotation.create_time
     *
     * @return the value of t_open_rotation.create_time
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public Long getCreate_time() {
        return create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_open_rotation.create_time
     *
     * @param create_time the value for t_open_rotation.create_time
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public void setCreate_time(Long create_time) {
        this.create_time = create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_open_rotation.update_time
     *
     * @return the value of t_open_rotation.update_time
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public Long getUpdate_time() {
        return update_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_open_rotation.update_time
     *
     * @param update_time the value for t_open_rotation.update_time
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public void setUpdate_time(Long update_time) {
        this.update_time = update_time;
    }
}