package com.jckj.model;

public class TOpenSchool {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_open_school.id
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_open_school.school_name
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    private String school_name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_open_school.describe
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    private String describe;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_open_school.phone
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_open_school.address
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_open_school.is_show
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    private Boolean is_show;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_open_school.is_delete
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    private Boolean is_delete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_open_school.create_time
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    private Long create_time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_open_school.update_time
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    private Long update_time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_open_school.id
     *
     * @return the value of t_open_school.id
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_open_school.id
     *
     * @param id the value for t_open_school.id
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_open_school.school_name
     *
     * @return the value of t_open_school.school_name
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public String getSchool_name() {
        return school_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_open_school.school_name
     *
     * @param school_name the value for t_open_school.school_name
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public void setSchool_name(String school_name) {
        this.school_name = school_name == null ? null : school_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_open_school.describe
     *
     * @return the value of t_open_school.describe
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public String getDescribe() {
        return describe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_open_school.describe
     *
     * @param describe the value for t_open_school.describe
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public void setDescribe(String describe) {
        this.describe = describe == null ? null : describe.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_open_school.phone
     *
     * @return the value of t_open_school.phone
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_open_school.phone
     *
     * @param phone the value for t_open_school.phone
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_open_school.address
     *
     * @return the value of t_open_school.address
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_open_school.address
     *
     * @param address the value for t_open_school.address
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_open_school.is_show
     *
     * @return the value of t_open_school.is_show
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public Boolean getIs_show() {
        return is_show;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_open_school.is_show
     *
     * @param is_show the value for t_open_school.is_show
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public void setIs_show(Boolean is_show) {
        this.is_show = is_show;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_open_school.is_delete
     *
     * @return the value of t_open_school.is_delete
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public Boolean getIs_delete() {
        return is_delete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_open_school.is_delete
     *
     * @param is_delete the value for t_open_school.is_delete
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public void setIs_delete(Boolean is_delete) {
        this.is_delete = is_delete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_open_school.create_time
     *
     * @return the value of t_open_school.create_time
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public Long getCreate_time() {
        return create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_open_school.create_time
     *
     * @param create_time the value for t_open_school.create_time
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public void setCreate_time(Long create_time) {
        this.create_time = create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_open_school.update_time
     *
     * @return the value of t_open_school.update_time
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public Long getUpdate_time() {
        return update_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_open_school.update_time
     *
     * @param update_time the value for t_open_school.update_time
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public void setUpdate_time(Long update_time) {
        this.update_time = update_time;
    }
}