package com.jckj.model;

public class TOpenStyle {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_open_style.id
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_open_style.student_id
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    private Integer student_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_open_style.school_id
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    private Integer school_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_open_style.picture
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    private String picture;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_open_style.video
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    private String video;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_open_style.is_show
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    private Boolean is_show;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_open_style.is_delete
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    private Boolean is_delete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_open_style.create_time
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    private Long create_time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_open_style.update_time
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    private Long update_time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_open_style.id
     *
     * @return the value of t_open_style.id
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_open_style.id
     *
     * @param id the value for t_open_style.id
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_open_style.student_id
     *
     * @return the value of t_open_style.student_id
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public Integer getStudent_id() {
        return student_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_open_style.student_id
     *
     * @param student_id the value for t_open_style.student_id
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public void setStudent_id(Integer student_id) {
        this.student_id = student_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_open_style.school_id
     *
     * @return the value of t_open_style.school_id
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public Integer getSchool_id() {
        return school_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_open_style.school_id
     *
     * @param school_id the value for t_open_style.school_id
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public void setSchool_id(Integer school_id) {
        this.school_id = school_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_open_style.picture
     *
     * @return the value of t_open_style.picture
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public String getPicture() {
        return picture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_open_style.picture
     *
     * @param picture the value for t_open_style.picture
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public void setPicture(String picture) {
        this.picture = picture == null ? null : picture.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_open_style.video
     *
     * @return the value of t_open_style.video
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public String getVideo() {
        return video;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_open_style.video
     *
     * @param video the value for t_open_style.video
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public void setVideo(String video) {
        this.video = video == null ? null : video.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_open_style.is_show
     *
     * @return the value of t_open_style.is_show
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public Boolean getIs_show() {
        return is_show;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_open_style.is_show
     *
     * @param is_show the value for t_open_style.is_show
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public void setIs_show(Boolean is_show) {
        this.is_show = is_show;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_open_style.is_delete
     *
     * @return the value of t_open_style.is_delete
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public Boolean getIs_delete() {
        return is_delete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_open_style.is_delete
     *
     * @param is_delete the value for t_open_style.is_delete
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public void setIs_delete(Boolean is_delete) {
        this.is_delete = is_delete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_open_style.create_time
     *
     * @return the value of t_open_style.create_time
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public Long getCreate_time() {
        return create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_open_style.create_time
     *
     * @param create_time the value for t_open_style.create_time
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public void setCreate_time(Long create_time) {
        this.create_time = create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_open_style.update_time
     *
     * @return the value of t_open_style.update_time
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public Long getUpdate_time() {
        return update_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_open_style.update_time
     *
     * @param update_time the value for t_open_style.update_time
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public void setUpdate_time(Long update_time) {
        this.update_time = update_time;
    }
}