package com.jckj.model;

public class TOpenNavigation {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_open_navigation.id
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_open_navigation.navigation_name
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    private String navigation_name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_open_navigation.is_delete
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    private Boolean is_delete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_open_navigation.create_time
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    private Long create_time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_open_navigation.update_time
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    private Long update_time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_open_navigation.id
     *
     * @return the value of t_open_navigation.id
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_open_navigation.id
     *
     * @param id the value for t_open_navigation.id
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_open_navigation.navigation_name
     *
     * @return the value of t_open_navigation.navigation_name
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public String getNavigation_name() {
        return navigation_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_open_navigation.navigation_name
     *
     * @param navigation_name the value for t_open_navigation.navigation_name
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public void setNavigation_name(String navigation_name) {
        this.navigation_name = navigation_name == null ? null : navigation_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_open_navigation.is_delete
     *
     * @return the value of t_open_navigation.is_delete
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public Boolean getIs_delete() {
        return is_delete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_open_navigation.is_delete
     *
     * @param is_delete the value for t_open_navigation.is_delete
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public void setIs_delete(Boolean is_delete) {
        this.is_delete = is_delete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_open_navigation.create_time
     *
     * @return the value of t_open_navigation.create_time
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public Long getCreate_time() {
        return create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_open_navigation.create_time
     *
     * @param create_time the value for t_open_navigation.create_time
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public void setCreate_time(Long create_time) {
        this.create_time = create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_open_navigation.update_time
     *
     * @return the value of t_open_navigation.update_time
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public Long getUpdate_time() {
        return update_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_open_navigation.update_time
     *
     * @param update_time the value for t_open_navigation.update_time
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public void setUpdate_time(Long update_time) {
        this.update_time = update_time;
    }
}