package com.jckj.model;

public class TOpenCourse {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_open_course.id
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_open_course.course_id
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    private String course_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_open_course.course_name
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    private String course_name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_open_course.photo
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    private String photo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_open_course.course_hour
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    private Integer course_hour;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_open_course.shaky_status
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    private Boolean shaky_status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_open_course.price
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    private Long price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_open_course.course_state
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    private Boolean course_state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_open_course.describe
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    private String describe;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_open_course.start_time
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    private Long start_time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_open_course.end_time
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    private Long end_time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_open_course.pay_number
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    private String pay_number;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_open_course.school_name
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    private String school_name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_open_course.is_show
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    private Boolean is_show;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_open_course.is_delete
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    private Boolean is_delete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_open_course.create_time
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    private Long create_time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_open_course.update_time
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    private Long update_time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_open_course.id
     *
     * @return the value of t_open_course.id
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_open_course.id
     *
     * @param id the value for t_open_course.id
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_open_course.course_id
     *
     * @return the value of t_open_course.course_id
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public String getCourse_id() {
        return course_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_open_course.course_id
     *
     * @param course_id the value for t_open_course.course_id
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public void setCourse_id(String course_id) {
        this.course_id = course_id == null ? null : course_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_open_course.course_name
     *
     * @return the value of t_open_course.course_name
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public String getCourse_name() {
        return course_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_open_course.course_name
     *
     * @param course_name the value for t_open_course.course_name
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public void setCourse_name(String course_name) {
        this.course_name = course_name == null ? null : course_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_open_course.photo
     *
     * @return the value of t_open_course.photo
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public String getPhoto() {
        return photo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_open_course.photo
     *
     * @param photo the value for t_open_course.photo
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public void setPhoto(String photo) {
        this.photo = photo == null ? null : photo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_open_course.course_hour
     *
     * @return the value of t_open_course.course_hour
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public Integer getCourse_hour() {
        return course_hour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_open_course.course_hour
     *
     * @param course_hour the value for t_open_course.course_hour
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public void setCourse_hour(Integer course_hour) {
        this.course_hour = course_hour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_open_course.shaky_status
     *
     * @return the value of t_open_course.shaky_status
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public Boolean getShaky_status() {
        return shaky_status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_open_course.shaky_status
     *
     * @param shaky_status the value for t_open_course.shaky_status
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public void setShaky_status(Boolean shaky_status) {
        this.shaky_status = shaky_status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_open_course.price
     *
     * @return the value of t_open_course.price
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public Long getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_open_course.price
     *
     * @param price the value for t_open_course.price
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public void setPrice(Long price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_open_course.course_state
     *
     * @return the value of t_open_course.course_state
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public Boolean getCourse_state() {
        return course_state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_open_course.course_state
     *
     * @param course_state the value for t_open_course.course_state
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public void setCourse_state(Boolean course_state) {
        this.course_state = course_state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_open_course.describe
     *
     * @return the value of t_open_course.describe
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public String getDescribe() {
        return describe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_open_course.describe
     *
     * @param describe the value for t_open_course.describe
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public void setDescribe(String describe) {
        this.describe = describe == null ? null : describe.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_open_course.start_time
     *
     * @return the value of t_open_course.start_time
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public Long getStart_time() {
        return start_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_open_course.start_time
     *
     * @param start_time the value for t_open_course.start_time
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public void setStart_time(Long start_time) {
        this.start_time = start_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_open_course.end_time
     *
     * @return the value of t_open_course.end_time
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public Long getEnd_time() {
        return end_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_open_course.end_time
     *
     * @param end_time the value for t_open_course.end_time
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public void setEnd_time(Long end_time) {
        this.end_time = end_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_open_course.pay_number
     *
     * @return the value of t_open_course.pay_number
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public String getPay_number() {
        return pay_number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_open_course.pay_number
     *
     * @param pay_number the value for t_open_course.pay_number
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public void setPay_number(String pay_number) {
        this.pay_number = pay_number == null ? null : pay_number.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_open_course.school_name
     *
     * @return the value of t_open_course.school_name
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public String getSchool_name() {
        return school_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_open_course.school_name
     *
     * @param school_name the value for t_open_course.school_name
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public void setSchool_name(String school_name) {
        this.school_name = school_name == null ? null : school_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_open_course.is_show
     *
     * @return the value of t_open_course.is_show
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public Boolean getIs_show() {
        return is_show;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_open_course.is_show
     *
     * @param is_show the value for t_open_course.is_show
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public void setIs_show(Boolean is_show) {
        this.is_show = is_show;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_open_course.is_delete
     *
     * @return the value of t_open_course.is_delete
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public Boolean getIs_delete() {
        return is_delete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_open_course.is_delete
     *
     * @param is_delete the value for t_open_course.is_delete
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public void setIs_delete(Boolean is_delete) {
        this.is_delete = is_delete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_open_course.create_time
     *
     * @return the value of t_open_course.create_time
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public Long getCreate_time() {
        return create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_open_course.create_time
     *
     * @param create_time the value for t_open_course.create_time
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public void setCreate_time(Long create_time) {
        this.create_time = create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_open_course.update_time
     *
     * @return the value of t_open_course.update_time
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public Long getUpdate_time() {
        return update_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_open_course.update_time
     *
     * @param update_time the value for t_open_course.update_time
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public void setUpdate_time(Long update_time) {
        this.update_time = update_time;
    }
}