package com.jckj.model;

public class TOpenIntegral {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_open_integral.id
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_open_integral.integral_number
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    private String integral_number;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_open_integral.is_delete
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    private Boolean is_delete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_open_integral.create_time
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    private Long create_time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_open_integral.update_time
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    private Long update_time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_open_integral.id
     *
     * @return the value of t_open_integral.id
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_open_integral.id
     *
     * @param id the value for t_open_integral.id
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_open_integral.integral_number
     *
     * @return the value of t_open_integral.integral_number
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public String getIntegral_number() {
        return integral_number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_open_integral.integral_number
     *
     * @param integral_number the value for t_open_integral.integral_number
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public void setIntegral_number(String integral_number) {
        this.integral_number = integral_number == null ? null : integral_number.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_open_integral.is_delete
     *
     * @return the value of t_open_integral.is_delete
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public Boolean getIs_delete() {
        return is_delete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_open_integral.is_delete
     *
     * @param is_delete the value for t_open_integral.is_delete
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public void setIs_delete(Boolean is_delete) {
        this.is_delete = is_delete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_open_integral.create_time
     *
     * @return the value of t_open_integral.create_time
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public Long getCreate_time() {
        return create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_open_integral.create_time
     *
     * @param create_time the value for t_open_integral.create_time
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public void setCreate_time(Long create_time) {
        this.create_time = create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_open_integral.update_time
     *
     * @return the value of t_open_integral.update_time
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public Long getUpdate_time() {
        return update_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_open_integral.update_time
     *
     * @param update_time the value for t_open_integral.update_time
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public void setUpdate_time(Long update_time) {
        this.update_time = update_time;
    }
}