package com.jckj.model;

public class TSaltsInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_salts_info.id
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_salts_info.student_name
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    private String student_name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_salts_info.salts_time
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    private Long salts_time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_salts_info.salts_cause
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    private String salts_cause;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_salts_info.salts_type
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    private Byte salts_type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_salts_info.is_delete
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    private Byte is_delete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_salts_info.create_time
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    private Long create_time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_salts_info.update_time
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    private Long update_time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_salts_info.salts_name
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    private String salts_name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_salts_info.id
     *
     * @return the value of t_salts_info.id
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_salts_info.id
     *
     * @param id the value for t_salts_info.id
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_salts_info.student_name
     *
     * @return the value of t_salts_info.student_name
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public String getStudent_name() {
        return student_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_salts_info.student_name
     *
     * @param student_name the value for t_salts_info.student_name
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public void setStudent_name(String student_name) {
        this.student_name = student_name == null ? null : student_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_salts_info.salts_time
     *
     * @return the value of t_salts_info.salts_time
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public Long getSalts_time() {
        return salts_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_salts_info.salts_time
     *
     * @param salts_time the value for t_salts_info.salts_time
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public void setSalts_time(Long salts_time) {
        this.salts_time = salts_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_salts_info.salts_cause
     *
     * @return the value of t_salts_info.salts_cause
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public String getSalts_cause() {
        return salts_cause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_salts_info.salts_cause
     *
     * @param salts_cause the value for t_salts_info.salts_cause
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public void setSalts_cause(String salts_cause) {
        this.salts_cause = salts_cause == null ? null : salts_cause.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_salts_info.salts_type
     *
     * @return the value of t_salts_info.salts_type
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public Byte getSalts_type() {
        return salts_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_salts_info.salts_type
     *
     * @param salts_type the value for t_salts_info.salts_type
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public void setSalts_type(Byte salts_type) {
        this.salts_type = salts_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_salts_info.is_delete
     *
     * @return the value of t_salts_info.is_delete
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public Byte getIs_delete() {
        return is_delete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_salts_info.is_delete
     *
     * @param is_delete the value for t_salts_info.is_delete
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public void setIs_delete(Byte is_delete) {
        this.is_delete = is_delete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_salts_info.create_time
     *
     * @return the value of t_salts_info.create_time
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public Long getCreate_time() {
        return create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_salts_info.create_time
     *
     * @param create_time the value for t_salts_info.create_time
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public void setCreate_time(Long create_time) {
        this.create_time = create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_salts_info.update_time
     *
     * @return the value of t_salts_info.update_time
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public Long getUpdate_time() {
        return update_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_salts_info.update_time
     *
     * @param update_time the value for t_salts_info.update_time
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public void setUpdate_time(Long update_time) {
        this.update_time = update_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_salts_info.salts_name
     *
     * @return the value of t_salts_info.salts_name
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public String getSalts_name() {
        return salts_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_salts_info.salts_name
     *
     * @param salts_name the value for t_salts_info.salts_name
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public void setSalts_name(String salts_name) {
        this.salts_name = salts_name == null ? null : salts_name.trim();
    }
}