package com.jckj.model;

public class TUserInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.id
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.user_pwd
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    private String user_pwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.user_name
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    private String user_name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.birthday
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    private String birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.welfare
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    private Integer welfare;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.user_role
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    private String user_role;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.user_sex
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    private String user_sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.user_photo
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    private String user_photo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.user_phone
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    private Integer user_phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.is_delete
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    private Boolean is_delete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.create_time
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    private Long create_time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.update_time
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    private Long update_time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.id
     *
     * @return the value of t_user_info.id
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.id
     *
     * @param id the value for t_user_info.id
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.user_pwd
     *
     * @return the value of t_user_info.user_pwd
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public String getUser_pwd() {
        return user_pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.user_pwd
     *
     * @param user_pwd the value for t_user_info.user_pwd
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public void setUser_pwd(String user_pwd) {
        this.user_pwd = user_pwd == null ? null : user_pwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.user_name
     *
     * @return the value of t_user_info.user_name
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public String getUser_name() {
        return user_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.user_name
     *
     * @param user_name the value for t_user_info.user_name
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public void setUser_name(String user_name) {
        this.user_name = user_name == null ? null : user_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.birthday
     *
     * @return the value of t_user_info.birthday
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public String getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.birthday
     *
     * @param birthday the value for t_user_info.birthday
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public void setBirthday(String birthday) {
        this.birthday = birthday == null ? null : birthday.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.welfare
     *
     * @return the value of t_user_info.welfare
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public Integer getWelfare() {
        return welfare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.welfare
     *
     * @param welfare the value for t_user_info.welfare
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public void setWelfare(Integer welfare) {
        this.welfare = welfare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.user_role
     *
     * @return the value of t_user_info.user_role
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public String getUser_role() {
        return user_role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.user_role
     *
     * @param user_role the value for t_user_info.user_role
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public void setUser_role(String user_role) {
        this.user_role = user_role == null ? null : user_role.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.user_sex
     *
     * @return the value of t_user_info.user_sex
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public String getUser_sex() {
        return user_sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.user_sex
     *
     * @param user_sex the value for t_user_info.user_sex
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public void setUser_sex(String user_sex) {
        this.user_sex = user_sex == null ? null : user_sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.user_photo
     *
     * @return the value of t_user_info.user_photo
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public String getUser_photo() {
        return user_photo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.user_photo
     *
     * @param user_photo the value for t_user_info.user_photo
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public void setUser_photo(String user_photo) {
        this.user_photo = user_photo == null ? null : user_photo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.user_phone
     *
     * @return the value of t_user_info.user_phone
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public Integer getUser_phone() {
        return user_phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.user_phone
     *
     * @param user_phone the value for t_user_info.user_phone
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public void setUser_phone(Integer user_phone) {
        this.user_phone = user_phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.is_delete
     *
     * @return the value of t_user_info.is_delete
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public Boolean getIs_delete() {
        return is_delete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.is_delete
     *
     * @param is_delete the value for t_user_info.is_delete
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public void setIs_delete(Boolean is_delete) {
        this.is_delete = is_delete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.create_time
     *
     * @return the value of t_user_info.create_time
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public Long getCreate_time() {
        return create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.create_time
     *
     * @param create_time the value for t_user_info.create_time
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public void setCreate_time(Long create_time) {
        this.create_time = create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.update_time
     *
     * @return the value of t_user_info.update_time
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public Long getUpdate_time() {
        return update_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.update_time
     *
     * @param update_time the value for t_user_info.update_time
     *
     * @mbg.generated Mon Aug 29 15:23:29 CST 2022
     */
    public void setUpdate_time(Long update_time) {
        this.update_time = update_time;
    }
}